# Generated by Django 3.2.8 on 2021-10-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='account_destiny',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='account_origin',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
